open_manipulator_chain:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 125

  # Position Controllers ---------------------------------------
  joint1_position:
    type: position_controllers/JointPositionController
    joint: joint1

  joint2_position:
    type: position_controllers/JointPositionController
    joint: joint2

  joint3_position:
    type: position_controllers/JointPositionController
    joint: joint3

  joint4_position:
    type: position_controllers/JointPositionController
    joint: joint4

  grip_joint_position:
    type: position_controllers/JointPositionController
    joint: grip_joint

  grip_joint_sub_position:
    type: position_controllers/JointPositionController
    joint: grip_joint_sub
